"""Generic PGD attack.

Deliberately model-agnostic: instead of hardcoding "attack the CE loss of
this model", `pgd_attack` takes a `loss_fn(x_adv) -> scalar` closure that
the caller builds. This lets the exact same attack loop serve:

  - standard Madry-style PGD-AT (maximize CE against the true label)
  - TRADES-style PGD (maximize KL divergence from the clean output
    distribution)
  - the optional obfuscation-risk ablation (maximize CE plus/minus the
    alignment loss -- see AlignConfig.inner_max_uses_alignment in
    config.py and the README section on adaptive evaluation)

By default (inner_max_uses_alignment=False), adversarial examples for the
proposed method are generated by *plain* PGD on CE, identical to the
Madry baseline -- the SAE alignment term only ever touches the outer
(defender's) loss. This is a deliberate design choice: it keeps the
attack step directly comparable across all methods and avoids the
attacker's objective depending on the very quantity we are trying to
regularize the model with.
"""
from __future__ import annotations

from typing import Callable, Optional

import torch
import torch.nn.functional as F


def _random_start(x: torch.Tensor, epsilon: float, norm: str) -> torch.Tensor:
    if norm == "linf":
        delta = torch.empty_like(x).uniform_(-epsilon, epsilon)
    elif norm == "l2":
        delta = torch.randn_like(x)
        flat = delta.view(delta.size(0), -1)
        flat = flat / flat.norm(dim=1, keepdim=True).clamp_min(1e-12)
        radius = torch.rand(x.size(0), 1, device=x.device) ** (1.0 / flat.size(1))
        flat = flat * radius * epsilon
        delta = flat.view_as(x)
    else:
        raise ValueError(f"Unknown norm '{norm}'")
    return delta


def _project(delta: torch.Tensor, epsilon: float, norm: str) -> torch.Tensor:
    if norm == "linf":
        return torch.clamp(delta, -epsilon, epsilon)
    elif norm == "l2":
        flat = delta.view(delta.size(0), -1)
        norms = flat.norm(dim=1, keepdim=True).clamp_min(1e-12)
        factor = torch.clamp(epsilon / norms, max=1.0)
        return (flat * factor).view_as(delta)
    else:
        raise ValueError(f"Unknown norm '{norm}'")


def pgd_attack(
    x: torch.Tensor,
    loss_fn: Callable[[torch.Tensor], torch.Tensor],
    epsilon: float,
    alpha: float,
    steps: int,
    norm: str = "linf",
    random_start: bool = True,
) -> torch.Tensor:
    """Returns x_adv = x + delta, clamped to [0, 1], maximizing loss_fn(x_adv)
    within an epsilon-ball of x under the given norm. `x` must already be
    detached (this function does not touch the computation graph of x
    itself, only of the perturbation)."""
    x = x.detach()
    if random_start:
        delta = _random_start(x, epsilon, norm)
        delta = torch.clamp(x + delta, 0.0, 1.0) - x
    else:
        delta = torch.zeros_like(x)

    for _ in range(steps):
        delta = delta.detach().requires_grad_(True)
        x_adv = x + delta
        with torch.enable_grad():
            loss = loss_fn(x_adv)
        grad = torch.autograd.grad(loss, delta, only_inputs=True)[0]

        with torch.no_grad():
            if norm == "linf":
                delta = delta + alpha * grad.sign()
            elif norm == "l2":
                flat_grad = grad.view(grad.size(0), -1)
                grad_norm = flat_grad.norm(dim=1, keepdim=True).clamp_min(1e-12)
                unit_grad = (flat_grad / grad_norm).view_as(grad)
                delta = delta + alpha * unit_grad
            else:
                raise ValueError(f"Unknown norm '{norm}'")
            delta = _project(delta, epsilon, norm)
            delta = torch.clamp(x + delta, 0.0, 1.0) - x

    return (x + delta).detach()


def make_ce_loss_fn(model, y: torch.Tensor) -> Callable[[torch.Tensor], torch.Tensor]:
    def _fn(x_adv):
        logits = model(x_adv)
        return F.cross_entropy(logits, y)

    return _fn


def make_trades_kl_loss_fn(model, clean_logits: torch.Tensor) -> Callable[[torch.Tensor], torch.Tensor]:
    """TRADES-style inner maximization: maximize KL(softmax(adv) || softmax(clean)).
    clean_logits must already be detached by the caller."""
    clean_probs = F.softmax(clean_logits.detach(), dim=1)

    def _fn(x_adv):
        adv_log_probs = F.log_softmax(model(x_adv), dim=1)
        return F.kl_div(adv_log_probs, clean_probs, reduction="batchmean")

    return _fn


def eval_mode_for_attack(model):
    """Context manager: switches model to eval() for adversarial-example
    generation (freezes BatchNorm running stats during the PGD inner loop,
    standard practice) and restores the previous mode afterwards."""

    class _Ctx:
        def __enter__(self_ctx):
            self_ctx.was_training = model.training
            model.eval()
            return model

        def __exit__(self_ctx, exc_type, exc_val, exc_tb):
            model.train(self_ctx.was_training)

    return _Ctx()
